version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  test:
    executor: win/default
    parameters:
      param_1:
        type: string
      param_2:
        type: string
        default: ''
      param_3:
        type: string
        default: ''
      param_4:
        type: string
        default: ''
    steps:
      - checkout
      - run: Get-Variable
      # - run:
      #     command: ./Set-CircleCiEnvironmentVariable.ps1
      #     shell: pwsh
      #     environment:
      #       inputs: << parameters.param_1 >>
      - run:
          command: ./test.ps1
workflows:
  test-workflow:
    jobs:
      - test:
          name: test1
          param_1: test
          
